export const restArray = [
    {
      id: 1,
      title: "Пицца плюс",
      time: 50,
      rating: 4.5,
      price: 900,
      type: "Пицца",
      image: "rest1.jpg",
    },
    {
      id: 2,
      title: "Тануки ",
      time: 50,
      rating: 4.5,
      price: 900,
      type: "Пицца",
      image: "rest2.jpg",
    },
    {
      id: 3,
      title: "FoodBand",
      time: 50,
      rating: 4.5,
      price: 900,
      type: "Пицца",
      image: "rest3.jpg",
    },
    {
      id: 4,
      title: "Жадина-пицца",
      time: 50,
      rating: 4.5,
      price: 900,
      type: "Пицца",
      image: "rest4.jpg",
    },
    {
      id: 5,
      title: "Точка еды",
      time: 50,
      rating: 4.5,
      price: 900,
      type: "Пицца",
      image: "rest5.jpg",
    },
    {
      id: 6,
      title: "PizzaBurger",
      time: 50,
      rating: 4.5,
      price: 900,
      type: "Пицца",
      image: "rest6.jpg",
    },
  ];